import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavBar } from "./NavBar";
import { PlaybackBar } from "./PlaybackBar";
import { SideBar } from "./SideBar";
import { PlaybackContextProvider } from "./PlaybackContextProvider";
import { getDb } from "@/lib/db";
import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cookieStore = await cookies()
  const userId = cookieStore.get('userId')?.value

  if (!userId) {
    console.log('No userId cookie found')
  }

  const db = getDb();

  const initialSongs = await db
    .selectFrom("songs")
    .innerJoin("albums", "songs.album_id", "albums.id")
    .innerJoin("authors", "albums.author_id", "authors.id")
    .select([
      "songs.id",
      "songs.name",
      "authors.name as author",
      "songs.duration",
    ])
    .limit(5)
    .execute();

  const likedSongIds =
    userId != null
      ? await db
          .selectFrom("user_liked_songs")
          .where("user_id", "=", Number(userId))
          .select("song_id")
          .execute()
      : null;

  const playlists =
    userId != null
      ? await db
          .selectFrom("playlists")
          .where("user_id", "=", Number(userId))
          .select(["id", "name"])
          .execute()
      : null;

  console.log(initialSongs);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <PlaybackContextProvider initialSongs={initialSongs}>
          <div className="font-sans grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20">
            <main className="flex flex-col gap-[32px] row-start-2 items-center sm:items-start">
              <div className="pb-4 pr-32">{children}</div>
              <div className="fixed top-0 bottom-0 right-0 pt-20 w-32">
                <SideBar />
              </div>
              <div className="fixed top-0 left-0 right-0">
                <NavBar />
              </div>
              <div className="fixed h-24 bg-base-100 bottom-0 left-0 right-0 inset-shadow-sm">
                <PlaybackBar
                initialSongs={initialSongs}
                likedSongIds={likedSongIds?.map((row) => row.song_id) ?? []}
                playlists={playlists ?? []}
                />
              </div>
            </main>
          </div>
        </PlaybackContextProvider>
      </body>
    </html>
  );
}
